# Sample Configuration for Subtitle Generation Pipeline
# Copy this to config.yaml and adjust settings as needed

# Video Settings
video:
  # YouTube URL to process (REQUIRED - set this or use --url command line argument)
  url: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID"
  # Directory for temporary downloads (relative to project root)
  tmp_downloads_dir: "tmp_downloads"
  # Video input language (auto-detected if not specified)
  input_language: ""

# ASR (Automatic Speech Recognition) Settings
asr:
  # Backend: "local" (faster-whisper) or "groq" (Groq API)
  backend: "groq"
  # Model for local transcription (base, small, medium, large, large-v2, large-v3)
  whisper_model: "base"
  # Model for Groq API transcription
  groq_model: "distil-whisper-large-v3-en"

# LLM (Large Language Model) Settings
llm:
  # Backend: "groq" (using Groq API)
  backend: "groq"
  # Model name for Groq API
  # Popular models: llama3-8b-8192, llama3-70b-8192, gemma-7b-it, mixtral-8x7b-32768
  model: "llama3-8b-8192"
  
  # Enhancement settings
  enhancer:
    # Enable transcript enhancement (grammar, punctuation, capitalization)
    enabled: true
    # Temperature for enhancement (0.0-1.0, lower = more deterministic)
    temperature: 0.0
  
  # Translation settings
  translator:
    # Enable translation
    enabled: false
    # Target language for translation (e.g., "Spanish", "French", "German", "Chinese")
    target_language: ""
    # Temperature for translation (0.0-1.0, slightly higher for more natural translations)
    temperature: 0.1

# Subtitle Settings
subtitles:
  # Mode: "soft" (embedded subtitles) or "burn" (burned-in subtitles)
  mode: "soft"
  # Box opacity for burned subtitles (0.0-1.0, only used if mode is "burn")
  box_opacity: 0.6

# API Settings
api:
  # Groq API key (REQUIRED for Groq backend)
  # You can also set this via GROQ_API_KEY environment variable
  # Get your key from: https://console.groq.com/keys
  groq_api_key: "gsk_YOUR_API_KEY_HERE"

# Processing Settings (usually don't need to change these)
processing:
  # Audio extraction settings
  audio:
    sample_rate: 16000
    mono: true
  
  # Output directories (relative to video_id working directory)
  output:
    audio_dir: "audio"
    transcripts_dir: "transcripts"
    enhanced_dir: "enhanced"
    translated_dir: "translated"
    subtitled_dir: "subtitled"

# Advanced Settings (usually don't need to change these)
advanced:
  # Faster-whisper settings for local transcription
  faster_whisper:
    device: "auto"
    compute_type: "float16"
    beam_size: 5
    vad_filter: true
    vad_parameters:
      min_silence_duration_ms: 500
    word_timestamps: false
  
  # Retry settings for API calls
  retry:
    max_attempts: 3
    delay_seconds: 1
